use std::fs;
use std::path::Path;

fn load_glyph(path: &Path) -> [u8; 7] {
    let img = image::open(path).expect(&format!("cannot open glyph: {}", path.display()));
    let img = img.to_luma8();
    assert_eq!(img.width(), 5, "glyph {} must be 5px wide", path.display());
    assert_eq!(img.height(), 7, "glyph {} must be 7px tall", path.display());
    let mut glyph = [0u8; 7];
    for row in 0..7 {
        let mut byte = 0u8;
        for col in 0..5 {
            let pixel = img.get_pixel(col, row)[0];
            if pixel < 128 {
                byte |= 1 << (4 - col);
            }
        }
        glyph[row as usize] = byte;
    }
    glyph
}

fn letter_index(c: char) -> Option<u8> {
    let idx = match c {
        'А' | 'а' => 0,
        'Б' | 'б' => 1,
        'В' | 'в' => 2,
        'Г' | 'г' => 3,
        'Д' | 'д' => 4,
        'Е' | 'е' => 5,
        'Ё' | 'ё' => 6,
        'Ж' | 'ж' => 7,
        'З' | 'з' => 8,
        'И' | 'и' => 9,
        'Й' | 'й' => 10,
        'К' | 'к' => 11,
        'Л' | 'л' => 12,
        'М' | 'м' => 13,
        'Н' | 'н' => 14,
        'О' | 'о' => 15,
        'П' | 'п' => 16,
        'Р' | 'р' => 17,
        'С' | 'с' => 18,
        'Т' | 'т' => 19,
        'У' | 'у' => 20,
        'Ф' | 'ф' => 21,
        'Х' | 'х' => 22,
        'Ц' | 'ц' => 23,
        'Ч' | 'ч' => 24,
        'Ш' | 'ш' => 25,
        'Щ' | 'щ' => 26,
        'Ъ' | 'ъ' => 27,
        'Ы' | 'ы' => 28,
        'Ь' | 'ь' => 29,
        'Э' | 'э' => 30,
        'Ю' | 'ю' => 31,
        'Я' | 'я' => 32,
        _ => return None,
    };
    Some(idx)
}

fn pack_word(s: &str) -> u32 {
    let chars: Vec<char> = s.chars().collect();
    assert_eq!(chars.len(), 5, "word '{}' is not 5 chars", s);
    let mut packed = 0u32;
    for (i, &c) in chars.iter().enumerate() {
        let idx = letter_index(c).unwrap_or_else(|| panic!("invalid char '{}' in word '{}'", c, s));
        packed |= (idx as u32) << (i * 6);
    }
    packed
}

fn unique_count(packed: u32) -> u32 {
    let mut mask = 0u64;
    for i in 0..5 {
        let letter = (packed >> (i * 6)) & 0x3F;
        mask |= 1u64 << letter;
    }
    mask.count_ones()
}

fn is_valid_word(s: &str) -> bool {
    if s.chars().count() != 5 {
        return false;
    }
    s.chars().all(|c| {
        matches!(c, 'А'..='Я' | 'а'..='я' | 'Ё' | 'ё')
    })
}

fn main() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dict_path = Path::new("data/dict.txt");

    println!("cargo:rerun-if-changed=data/dict.txt");

    let content = fs::read_to_string(dict_path).expect("cannot read data/dict.txt");
    let lines: Vec<&str> = content
        .lines()
        .map(|l| l.trim())
        .filter(|l| !l.is_empty())
        .collect();

    eprintln!("Total lines: {}", lines.len());

    let valid: Vec<&&str> = lines.iter().filter(|l| is_valid_word(l)).collect();
    eprintln!("Valid 5-letter Russian words: {}", valid.len());
    eprintln!("Skipped: {}", lines.len() - valid.len());

    let packed: Vec<u32> = valid.iter().map(|w| pack_word(w)).collect();

    // Compute unique letter scores and find best openers
    let mut indexed: Vec<(usize, u32, u32)> = packed
        .iter()
        .enumerate()
        .map(|(i, &p)| (i, p, unique_count(p)))
        .collect();
    indexed.sort_by(|a, b| b.2.cmp(&a.2).then_with(|| a.0.cmp(&b.0)));
    let best_indices: Vec<u16> = indexed
        .iter()
        .take(10)
        .map(|(i, _, _)| *i as u16)
        .collect();

    // Generate Rust source (compile-time constants, NO WORDS array)
    let mut out = String::new();
    out.push_str("// This file is auto-generated by build.rs\n");
    out.push_str("#[allow(dead_code)]\n\n");

    out.push_str(&format!("pub const WORD_COUNT: usize = {};\n\n", packed.len()));

    out.push_str("pub const BEST_OPENERS: &[u16] = &[\n");
    for &i in &best_indices {
        out.push_str(&format!("    {},\n", i));
    }
    out.push_str("];\n");

    let out_path = format!("{}/dict_data.rs", out_dir);
    fs::write(&out_path, out).expect("cannot write output");
    eprintln!("Generated: {}", out_path);

    // Append CYR_GLYPHS from PNG source images
    let glyphs_dir = Path::new("data/glyphs");
    println!("cargo:rerun-if-changed=data/glyphs/");
    let mut glyph_out = String::new();
    glyph_out.push_str("\n\n// Generated by build.rs from data/glyphs/*.png\n");
    glyph_out.push_str("pub const CYR_GLYPHS: [[u8; 7]; 33] = [\n");
    let glyph_names = [
        "А", "Б", "В", "Г", "Д", "Е", "Ё", "Ж", "З", "И", "Й", "К", "Л",
        "М", "Н", "О", "П", "Р", "С", "Т", "У", "Ф", "Х", "Ц", "Ч", "Ш",
        "Щ", "Ъ", "Ы", "Ь", "Э", "Ю", "Я",
    ];
    for idx in 0..33 {
        let png_path = glyphs_dir.join(format!("{}.png", idx));
        let glyph = load_glyph(&png_path);
        glyph_out.push_str(&format!("    // {}\n", glyph_names[idx]));
        glyph_out.push_str(&format!(
            "    [{}],\n",
            glyph
                .iter()
                .map(|b| format!("0x{:02X}", b))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    glyph_out.push_str("];\n");
    // Append to existing file
    let existing = fs::read_to_string(&out_path).expect("cannot read existing output");
    fs::write(&out_path, existing + &glyph_out).expect("cannot write glyph output");
    eprintln!("Appended CYR_GLYPHS to: {}", out_path);

    // Generate binary dictionary file for SD card
    let bin_path = format!("{}/dict.bin", out_dir);
    let mut bin_data = Vec::with_capacity(4 + packed.len() * 4);
    bin_data.extend_from_slice(&(packed.len() as u32).to_le_bytes());
    for &w in &packed {
        bin_data.extend_from_slice(&w.to_le_bytes());
    }
    fs::write(&bin_path, &bin_data).expect("cannot write dict.bin");
    // Also write to project root for easy access
    let root_path = Path::new("dict.bin");
    fs::write(&root_path, &bin_data).expect("cannot write project dict.bin");
    let size = bin_data.len();
    eprintln!("Generated dict.bin ({} bytes)", size);
    eprintln!("  out-dir: {}", bin_path);
    eprintln!("  project: {}", root_path.display());
    eprintln!();
    eprintln!("*** IMPORTANT: Copy dict.bin to your Flipper Zero SD card at:");
    eprintln!("    /ext/apps/Wordle/dict.bin");
    eprintln!("    (alongside wordle-solver.fap)");
    eprintln!();

    eprintln!("Packed {} words into {} bytes", packed.len(), packed.len() * 4);
    eprintln!("Best openers: {:?}", best_indices);
    for &i in &best_indices {
        let w = valid[i as usize];
        let p = packed[i as usize];
        eprintln!("  {} (idx={}, unique={})", w, i, unique_count(p));
    }
}
